"""Stage 1 — collection driver for HJ-SAC.

Episodes run on the run.py-style stack (TickChunkedController: vanilla
nominal + per-tick hook) via RolloutController mode='collect'. Per control
tick at 25 Hz the frozen encoder tokens, analytic body features, and the
privileged h are captured; dtheta stored per entry is the COMMANDED action
of that tick (planner a_nom / actor / perturbation — see action_source).

No termination on violation — the avoid-Bellman needs transitions in the
unsafe region. episode_id/done written from step zero.

Usage:
    python -m main.train.collect            (from CEHJ_safe/)
    python main/train/collect.py --episodes 25
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path

import numpy as np
import torch

if __package__ in (None, ""):
    import sys
    from pathlib import Path

    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    __package__ = "main.train"
CEHJ_ROOT = Path(__file__).resolve().parents[2]

from main.train.buffer import StepBuffer  # noqa: E402
from main.train.config import FrozenConfig, apply_embodiment_selection  # noqa: E402
from main.network.encoder import HoloBrainEncoder  # noqa: E402

CKPT_DIR = Path(
    os.environ.get("HOLOBRAIN_CKPT", "/root/autodl-tmp/HoloBrain/HoloBrain_v0.0_GD")
)


def make_kinematics(ckpt_dir: Path, embodiment: str = "piper"):
    """HoloBrain MultiArmKinematics for the given embodiment.

    piper / ARX-X5 / ur5-wsg: 14-dim joint_state [L6, gripL, R6, gripR].
    franka-panda: 16-dim [L7, gripL, R7, gripR], dual-arm URDF generated by
    tests/gen_franka_dualarm_urdf.py in the same convention (left arm at the
    root, right arm at (0, -0.6, 0)).
    """
    from robo_orchard_lab.dataset.horizon_manipulation.transforms import (
        MultiArmKinematics,
    )

    assets = Path(__file__).resolve().parents[2] / "assets" / "urdf"
    if embodiment == "aloha-agilex":
        # HoloBrain's own robotwin2_0 processor uses DualArmKinematics on
        # this exact URDF (fl_/fr_ links) — natural parity, defaults are the
        # aloha layout (arm joints 10-15/18-23, fingers merged per arm)
        from robo_orchard_lab.dataset.robotwin.transforms import (
            DualArmKinematics,
        )

        return DualArmKinematics(
            urdf=str(ckpt_dir / "urdf" / "arx5_description_isaac.urdf")
        )
    if embodiment == "franka-panda":
        return MultiArmKinematics(
            urdf=str(assets / "franka_panda_dualarm.urdf"),
            arm_link_keys=[
                [f"left_panda_link{i}" for i in range(1, 8)],
                [f"right_panda_link{i}" for i in range(1, 8)],
            ],
            arm_joint_id=[list(range(7)), list(range(9, 16))],
            finger_keys=[
                ["left_panda_leftfinger", "left_panda_rightfinger"],
                ["right_panda_leftfinger", "right_panda_rightfinger"],
            ],
        )
    if embodiment == "ARX-X5":
        return MultiArmKinematics(
            urdf=str(assets / "arx_x5_dualarm.urdf"),
            arm_link_keys=[
                [f"left_link{i}" for i in range(1, 7)],
                [f"right_link{i}" for i in range(1, 7)],
            ],
            arm_joint_id=[list(range(6)), list(range(8, 14))],
            finger_keys=[
                ["left_link7", "left_link8"],
                ["right_link7", "right_link8"],
            ],
        )
    if embodiment == "ur5-wsg":
        return MultiArmKinematics(
            urdf=str(ckpt_dir / "urdf" / "robotwin2_dual_arm_ur5_wsg.urdf"),
            arm_link_keys=[
                [f"left_{n}" for n in (
                    "shoulder_link", "upper_arm_link", "forearm_link",
                    "wrist_1_link", "wrist_2_link", "wrist_3_link")],
                [f"right_{n}" for n in (
                    "shoulder_link", "upper_arm_link", "forearm_link",
                    "wrist_1_link", "wrist_2_link", "wrist_3_link")],
            ],
            arm_joint_id=[list(range(6)), list(range(8, 14))],
            finger_keys=[
                ["left_gripper_left", "left_gripper_right"],
                ["right_gripper_left", "right_gripper_right"],
            ],
        )
    return MultiArmKinematics(
        urdf=str(ckpt_dir / "urdf" / "piper_description_dualarm.urdf"),
        arm_link_keys=[
            [f"left_link{i}" for i in range(1, 7)],
            [f"right_link{i}" for i in range(1, 7)],
        ],
        arm_joint_id=[list(range(6)), list(range(8, 14))],
        finger_keys=[["left_link7"], ["right_link7"]],
    )


ARM_DISTANCE = {"ur5-wsg": 0.8}  # ckpt dual-ur5 URDF mounts the arms 0.8 m apart


def make_training_env(cfg: FrozenConfig, seed: int, control_freq: float = 25.0):
    """Env built exactly like run.py's: controller install, on-path obstacle
    present in the scene, cuRobo world refreshed. The expert/nominal ignores
    the obstacle in planning but plays through it physically — that is where
    the unsafe transitions (h < 0) come from.
    """
    from main.envs.controller import CuroboIKController
    from main.envs.env import Env
    from main.envs.obstacle import choose_and_spawn, update_curobo_world

    CuroboIKController.install()
    env = Env(cfg.task, cfg.embodiment, seed,
              arm_distance=ARM_DISTANCE.get(cfg.embodiment, 0.6),
              control_freq=control_freq)
    # corridor t: config override, else the run.py sampler (sweep parity)
    if cfg.obstacle_t is not None:
        t = float(cfg.obstacle_t)
    else:
        from main.envs.run import _corridor_t

        t = _corridor_t(seed)
    actor, xyz, half, _arm = choose_and_spawn(
        env, cfg.obstacle_mode, "geometric", t, "auto",
        obstacle_model=getattr(cfg, "obstacle_model", "086_woodenblock"),
    )
    env.obstacle = actor
    env.obstacle_xyz = xyz
    env.obstacle_half = half
    # Cached MotionGen may still hold a cuboid from a previous episode.
    update_curobo_world(env.robot)
    return env


def episode_schedule(cfg: FrozenConfig, n_episodes: int, seed: int = 0):
    """Fixed cyclic schedule over the shuffled (task, embodiment) product —
    every one of the len(task_choices) x len(embodiment_choices)
    combinations appears floor(n / n_combos) times, so counts are exactly
    balanced (IID sampling leaves the combos badly unbalanced)."""
    import itertools

    combos = list(itertools.product(
        list(cfg.task_choices), list(cfg.embodiment_choices)
    ))
    rng = np.random.RandomState(seed)
    rng.shuffle(combos)
    return [combos[i % len(combos)] for i in range(n_episodes)]


def sample_scene(cfg: FrozenConfig, rng: np.random.RandomState,
                 task: str | None = None, embodiment: str | None = None):
    """One randomized cfg for a scene init: task/embodiment given (cyclic
    schedule) or drawn at random; obstacle from obstacle_choices; obstacle
    placement 80/20 on_path/off_path (independent draw — avoids confounding
    the filter engaging with the obstacle being in the way)."""
    import dataclasses

    task = task or str(rng.choice(list(cfg.task_choices)))
    embodiment = embodiment or str(rng.choice(list(cfg.embodiment_choices)))
    obstacle = str(rng.choice(list(cfg.obstacle_choices)))
    mode = "off_path" if rng.rand() < cfg.off_path_frac else "on_path"
    return dataclasses.replace(
        cfg, task=task, embodiment=embodiment, obstacle_model=obstacle,
        obstacle_mode=mode,
    )


def _load_follow_models(ckpt_path: Path, built: dict | None = None,
                        cfg: "FrozenConfig | None" = None) -> tuple:
    """Build (once) and (re)load policy modules from a training checkpoint —
    the --follow side of async online collection."""
    from main.network.encoder import RobotInjection
    from main.network.heads import PolicyEncoder, TokenActor, TwinCritic
    from main.network.trunk import GeometricTrunk

    if built is None:
        # softmin temperature must MATCH training (train.py scales the
        # config's physical metres by h_scale); it is a plain attribute,
        # not part of the state_dict, so loading cannot fix a wrong value
        T = (float(cfg.softmin_T) * float(getattr(cfg, "h_scale", 1.0))
             if cfg is not None else 0.02)
        geo = not getattr(cfg, "ablate_geometry", False)
        injection = RobotInjection(
            use_body_features=not getattr(cfg, "ablate_injection", False)
        ).cuda().eval()
        trunk = GeometricTrunk(geo=geo).cuda().eval()
        built = {
            "policy_enc": PolicyEncoder(injection, trunk).cuda().eval(),
            "actor": TokenActor().cuda().eval(),
            "critics": TwinCritic(temperature=T, geo=geo).cuda().eval(),
        }
    ckpt = torch.load(ckpt_path, map_location="cuda", weights_only=True)
    built["policy_enc"].injection.load_state_dict(ckpt["injection"])
    built["policy_enc"].trunk.load_state_dict(ckpt["trunk"])
    built["actor"].load_state_dict(ckpt["actor"])
    built["critics"].load_state_dict(ckpt["critics"])
    return built["policy_enc"], built["actor"], built["critics"], built


def collect(cfg: FrozenConfig, out_root: Path, buf: StepBuffer | None = None,
            episode_offset: int = 0, encoder=None, models=None,
            round_index: int = 0, watch: bool = False,
            follow: Path | None = None, capacity: int | None = None,
            success_only: bool = False, max_slot_retries: int = 0,
            record_video: bool = False, metrics=None,
            video_dir=None, video_filter_only: bool = False,
            buffer_dir=None) -> Path:
    """Collect episodes with the run.py-style controller stack
    (TickChunkedController) via RolloutController mode='collect'. Per-tick
    encoder tokens + body features + h are written to the buffer; dtheta is
    the commanded action of that tick.

    Episode structure: a fixed cyclic schedule over the shuffled
    (task, embodiment) product (exact balance); per episode, independent
    draws for obstacle placement (off_path_frac) and behavior policy
    (filter_episode_frac with the HJ filter when models are given; round 0
    is always nominal-only). Episodes whose obstacle fails to spawn are
    re-drawn into the same schedule slot (h = +inf would NaN the target).

    watch=True: keep collecting (cycling the schedule) until the buffer is
    full — the async online mode; pair with a trainer that calls
    buf.refresh(). follow=<checkpoint.pt>: reload the filter weights
    whenever the trainer publishes a newer checkpoint.

    success_only=True (warmup buffers): keep only episodes whose task
    succeeded — failures are rolled back out of the buffer and the slot is
    retried with a fresh scene (up to max_slot_retries). n_episodes then
    counts KEPT episodes: for a warmup buffer use
    n_episodes = 10 * len(tasks) * len(embodiments). ONE shared warmup
    buffer covers all embodiments — leave-one-out runs filter the held-out
    embodiment at sample time (StepBuffer.set_embodiment_filter), so do
    NOT pass --leave-out during warmup collection.

    record_video=True: write a panel video per ATTEMPT to
    out_root/videos/ (ep<slot>_a<attempt>_...mp4) — failed attempts are
    kept on disk too, so warmup retries can be debugged visually.
    """
    from main.train.rollout import RolloutController  # lazy: rollout imports us

    out_root = Path(out_root).resolve()  # RoboTwin chdirs during env setup
    out_root.mkdir(parents=True, exist_ok=True)
    cfg.save(out_root / "config.json")  # train.py loads this

    if encoder is None:
        encoder = HoloBrainEncoder(str(CKPT_DIR), device="cuda")
    kins = {}  # per-embodiment kinematics, built on first use

    if buf is None:
        # buffer_dir override: the memmap is the training hot path (~80 MB
        # random reads per grad step) — keep it on LOCAL disk, not a
        # network FS (/autodl-fs quotas and ~100 MB/s reads stall training)
        buf_dir = Path(buffer_dir).resolve() if buffer_dir else out_root / "buffer"
        if (buf_dir / "header.json").exists():
            # async online: the warmup collector already created it — never
            # rewrite the header (it would reset n for the reading trainer)
            buf = StepBuffer(buf_dir)
        else:
            if capacity is None and watch:
                raise ValueError("--watch needs --capacity (the buffer size)")
            if capacity is None:
                capacity = cfg.n_episodes * (cfg.max_steps_per_episode + 2)
            buf = StepBuffer(buf_dir, capacity=capacity,
                             header=cfg.to_dict())

    rng = np.random.RandomState(0)
    schedule = episode_schedule(cfg, cfg.n_episodes, seed=round_index)
    t_start = time.time()
    n_written = 0
    n_skipped = {"on_path": 0, "off_path": 0}
    n_fallback = 0  # failed episodes kept for coverage (success-only cap)
    follow_path = Path(follow) if follow else None
    follow_mtime = None
    built = None  # lazily-built model modules for --follow reloads

    ep = 0          # schedule slot (advances per KEPT episode)
    attempt = 0     # every rollout attempt (drives the scene seed)
    slot_retries = 0
    while True:
        if not watch and ep >= cfg.n_episodes:
            break
        if watch and len(buf) >= buf.capacity:
            print("[collect] buffer full; watch mode done")
            break
        if follow_path is not None:
            if follow_path.exists():
                mt = follow_path.stat().st_mtime
                if mt != follow_mtime:
                    try:
                        policy_enc, actor, critics, built = (
                            _load_follow_models(follow_path, built, cfg)
                        )
                        models = (policy_enc, actor, critics)
                        follow_mtime = mt
                        print(f"[collect] follow: reloaded {follow_path}")
                    except Exception as exc:
                        # a torn/unreadable checkpoint must not kill the
                        # watcher — keep the current weights and retry next
                        # episode (save is atomic via tmp+replace, so this
                        # is only a belt-and-braces guard)
                        print(f"[collect] follow: load failed ({exc}); "
                              f"keeping previous weights")
            elif models is None:
                print("[collect] follow: no checkpoint yet; collecting nominal")
        task_ep, emb_ep = schedule[ep % len(schedule)]
        # total spawn guarantee: with h = d_block only, an obstacle-free
        # episode would store h = +inf and NaN the Bellman target — re-draw
        # the slot (keeping the SAME task/embodiment) instead
        ro = None
        for _retry in range(5):
            cfg_ep = sample_scene(cfg, rng, task_ep, emb_ep) \
                if cfg.randomize_scenes else cfg
            if cfg_ep.embodiment not in kins:
                kins[cfg_ep.embodiment] = make_kinematics(CKPT_DIR, cfg_ep.embodiment)
            # behavior policy: filter episodes only when models exist and
            # the draw passes; round 0 (no models) is always nominal-only
            use_filter = (
                models is not None
                and rng.rand() < cfg.filter_episode_frac
            )
            try:
                candidate = RolloutController(
                    cfg_ep, seed=episode_offset + attempt, mode="collect",
                    encoder=encoder, kin=kins[cfg_ep.embodiment],
                    policy_enc=models[0] if models else None,
                    actor=models[1] if models else None,
                    critics=models[2] if models else None,
                    filter_active=use_filter,
                    buf=buf, episode_id=episode_offset + attempt,
                    perturb_prob=cfg_ep.perturb_prob, rng=rng,
                    max_steps=int(cfg_ep.max_steps_per_episode * 250.0 / 25.0),
                )
            except Exception as exc:
                # scene setup itself can fail (bad seed: unstable object
                # spawn, grasp planner edge cases) — treat as a re-draw
                print(f"[collect] ep {ep}: env setup failed ({exc}); "
                      f"re-drawing")
                attempt += 1
                continue
            if candidate.env.obstacle is not None:
                ro = candidate
                break
            print(f"[collect] ep {ep}: spawn failed for {cfg_ep.task}/"
                  f"{cfg_ep.embodiment}; re-drawing")
            candidate.env.close()
        if ro is None:
            n_skipped[cfg_ep.obstacle_mode] = n_skipped.get(cfg_ep.obstacle_mode, 0) + 1
            print(f"[collect] ep {ep}: 5 spawn failures; skipping episode")
            slot_retries = 0  # don't carry the failed slot's count forward
            ep += 1
            continue
        print(f"ep {ep}: {cfg_ep.embodiment} / {cfg_ep.task} / "
              f"{cfg_ep.obstacle_model} / {cfg_ep.obstacle_mode} / "
              f"{'FILTER' if use_filter else 'nominal'}")
        video = None
        # video_filter_only: record only filter-active episodes (nominal-only
        # episodes carry no filter signal — training wants those videos)
        if record_video and (use_filter or not video_filter_only):
            from main.train.eval_utils import PanelVideoWriter

            vid_dir = Path(video_dir) if video_dir else out_root / "videos"
            vid_dir.mkdir(parents=True, exist_ok=True)
            video = PanelVideoWriter(
                vid_dir / (f"ep{ep:04d}_a{attempt:03d}_"
                           f"{cfg_ep.embodiment}_{cfg_ep.task}_"
                           f"{cfg_ep.obstacle_mode}.mp4"),
                fps=25.0, h_scale=float(getattr(cfg_ep, "h_scale", 1.0)),
            )
            ro.video = video
        n_before = len(buf)
        success = False
        trace = {}
        try:
            trace = ro.run()
            success = bool(trace["success"])
        except AssertionError as exc:
            if "buffer full" in str(exc):
                # watch mode hit capacity mid-episode — normal termination
                print("[collect] buffer full mid-episode; stopping")
                if video is not None:
                    video.close()
                break
            import traceback

            traceback.print_exc()
        except Exception:
            import traceback

            traceback.print_exc()
        finally:
            if video is not None:
                video.close()
        attempt += 1
        if success_only and not success:
            slot_retries += 1
            cap = (max_slot_retries if max_slot_retries > 0
                   else (10 if cfg_ep.embodiment == "piper" else 50))
            if slot_retries <= cap:
                # success-only warmup: roll back the failed episode and
                # retry the same slot with a fresh scene (new seed)
                buf.discard_to(n_before)
                buf.flush()
                print(f"[collect] ep {ep} failed (attempt {slot_retries}/"
                      f"{cap}); retrying with a new scene")
                continue
            # cap exhausted: keep this failed episode anyway — the HJ
            # h-signal is intact, and the (task, embodiment) combo keeps
            # its schedule coverage (some combos are unreachable, e.g.
            # piper place_can_basket)
            print(f"[collect] ep {ep}: {cap} failures — "
                  f"keeping a failed episode for coverage "
                  f"(task {cfg_ep.task} / {cfg_ep.embodiment})")
            n_fallback += 1
            slot_retries = 0
            n_written = len(buf)
            buf.flush()
            ep += 1
            continue
        slot_retries = 0
        n_written = len(buf)
        # filter-metric record: only kept, filter-active episodes — nominal-
        # only episodes say nothing about the filter (round_metrics renders
        # the per-combo heatmaps during training)
        if metrics is not None and use_filter and trace:
            from main.train.eval_utils import compute_trace_metrics

            metrics.record(
                round_index, cfg_ep.task, cfg_ep.embodiment,
                compute_trace_metrics(trace, float(cfg_ep.h_scale)),
            )
        print(
            f"ep {ep} done: success={success} "
            f"steps={n_written} ({n_written / (time.time() - t_start):.1f}/s) "
            f"realized/cmd={trace.get('mean_realized_ratio', float('nan')):.2f}"
        )
        buf.flush()
        ep += 1

    buf.flush()
    print(f"spawn skips by mode: {n_skipped}; kept-failed episodes: {n_fallback}")
    print(f"\ncollection done: {n_written} steps in {time.time() - t_start:.0f}s")
    return out_root / "buffer"


def json_dumps(d) -> str:
    import json

    class Enc(json.JSONEncoder):
        def default(self, o):
            if isinstance(o, (np.floating, np.integer)):
                return float(o)
            if isinstance(o, np.bool_):
                return bool(o)
            return str(o)

    return json.dumps(d, cls=Enc)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--episodes", type=int, default=25,
                   help="episodes per collect call (warmup batch size; in "
                        "--watch mode this only sizes the schedule cycle)")
    p.add_argument("--task", default="stack_blocks_two")
    p.add_argument("--embodiment", default="piper")
    p.add_argument("--filter-margin", type=float, default=None,
                   help="metres: safe actor drives while Q(s,a_nom) "
                        "< margin (0 = only predicted penetration)")
    p.add_argument("--leave-out", default=None,
                   help="leave-one-out: exclude this embodiment from the pool")
    p.add_argument("--only-embodiment", default=None,
                   help="finetune phase: collect ONLY this embodiment")
    p.add_argument("--capacity", type=int, default=0,
                   help="buffer capacity in steps; 0 = episodes x "
                        "(max_steps+2). Size for the TOTAL run when using "
                        "--watch (memmap allocation is fixed at creation)")
    p.add_argument("--watch", action="store_true",
                   help="async online mode: keep collecting until the buffer "
                        "is full (pair with a trainer that refreshes)")
    p.add_argument("--success-only", action="store_true",
                   help="warmup buffers: keep only successful episodes "
                        "(failures are rolled back and retried with a fresh "
                        "scene, up to --max-slot-retries)")
    p.add_argument("--record-video", action="store_true",
                   help="write a panel video per attempt to <out>/videos/ "
                        "(kept for failed attempts too, for debugging)")
    p.add_argument("--max-slot-retries", type=int, default=0,
                   help="success-only retry cap per slot; 0 = per-embodiment "
                        "policy (piper 10, others 50)")
    p.add_argument("--follow", type=Path, default=None,
                   help="reload filter weights whenever this checkpoint "
                        "changes (the trainer saves it every "
                        "checkpoint_every steps)")
    p.add_argument("--out", type=Path, default=CEHJ_ROOT / "data" / "smoke")
    p.add_argument("--buffer-dir", type=Path, default=None,
                   help="memmap location (default <out>/buffer); use "
                        "local disk, not network FS — sampling is the "
                        "training hot path")
    args = p.parse_args()
    cfg = FrozenConfig(task=args.task, embodiment=args.embodiment,
                       n_episodes=args.episodes)
    apply_embodiment_selection(cfg, args.leave_out, args.only_embodiment)
    if getattr(args, "filter_margin", None) is not None:
        cfg.filter_margin = args.filter_margin
    collect(cfg, args.out, watch=args.watch, follow=args.follow,
            capacity=args.capacity or None, success_only=args.success_only,
            max_slot_retries=args.max_slot_retries,
            record_video=args.record_video, buffer_dir=args.buffer_dir)


if __name__ == "__main__":
    main()
