_wandb:
    value:
        cli_version: 0.28.2
        e:
            7sw97kt1a30zq15icipbutahdy2imamx:
                email: 754773895@qq.com
                executable: /root/miniconda3/envs/RoboTwin/bin/python
                git:
                    commit: 9e662cb7db589991214acf5d25afe7c6723f0985
                    remote: https://ghfast.top/https://github.com/tabz23/CEHJ_safe.git
                host: autodl-pro-787206fb5c5e
                os: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
                program: <python with no main file>
                python: CPython 3.10.20
                root: /root/autodl-tmp/CEHJ_safe
                startedAt: "2026-08-28T00:17:50.040488Z"
                writerId: 7sw97kt1a30zq15icipbutahdy2imamx
        m: []
        python_version: 3.10.20
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.28.2
            "12": 0.28.2
            "13": linux-x86_64
test:
    value: true
